### ISSUE TITLE
Replacing useBrowserEffect with setting latestRef inline

### ISSUE THREAD

**Issue by shkreios** [scottrippey/react-use-event-hook#8]
Foremost, thank you for this nice library. 

I am curious if the `useBrowserEffect` for setting the `latestRef` is necessary and if it can't be replaced with simply calling `latestRef.current = callback` inline i.e. replacing
```ts
useBrowserEffect(() => {
    latestRef.current = callback;
  }, [callback]);
```
with
```ts
latestRef.current = callback;
```

**Comment by scottrippey** [comment]
In the official RFC, this was discussed.  To sum up the reasons for wrapping inside `useBrowserEffect`: 

When React performs a render, if a component is unmounted, then it will run the cleanup effects, then finally execute new effects.
So, we actually want the "cleanup effects" to be able to access the OLD callbacks.  Therefore, we don't update during render; we update the callback in between cleanup and new effects.

Hopefully that made sense, it wasn't a _great_ explanation, but suffice to say: there's a narrow use-case where the React lifecycle is important.

**Comment by shkreios** [comment]
Yes makes perfect sense thank you very much
